version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"

  postgres:
    image: postgres:11
    container_name: db
    env_file: .env
    ports:
      - 5432:5432
